"use client"
// ============================================================
// SmartFood AI — Notification Center
// ============================================================
import { useStore, useMyNotifications, unreadCount } from "@/lib/store"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { EmptyState, SectionHeader, timeAgo, StatusBadge } from "./shared"
import {
  Bell, CheckCheck, UtensilsCrossed, CheckCircle2, HandHeart, Truck, Bike,
  AlertTriangle, Thermometer, HeartHandshake, ShieldCheck, Sparkles, Info,
} from "lucide-react"

const KIND_ICON: Record<string, { icon: React.ReactNode; cls: string }> = {
  "free-food": { icon: <UtensilsCrossed className="h-4 w-4" />, cls: "bg-emerald-100 text-emerald-700" },
  "request-accepted": { icon: <CheckCircle2 className="h-4 w-4" />, cls: "bg-teal-100 text-teal-700" },
  "donation-received": { icon: <HandHeart className="h-4 w-4" />, cls: "bg-amber-100 text-amber-700" },
  "delivery-request": { icon: <Truck className="h-4 w-4" />, cls: "bg-lime-100 text-lime-700" },
  "delivery-accepted": { icon: <Bike className="h-4 w-4" />, cls: "bg-lime-100 text-lime-700" },
  "expiry-alert": { icon: <AlertTriangle className="h-4 w-4" />, cls: "bg-orange-100 text-orange-700" },
  "storage-warning": { icon: <Thermometer className="h-4 w-4" />, cls: "bg-red-100 text-red-700" },
  "community-help": { icon: <HeartHandshake className="h-4 w-4" />, cls: "bg-rose-100 text-rose-700" },
  verification: { icon: <ShieldCheck className="h-4 w-4" />, cls: "bg-violet-100 text-violet-700" },
  "production-warning": { icon: <Sparkles className="h-4 w-4" />, cls: "bg-teal-100 text-teal-700" },
  info: { icon: <Info className="h-4 w-4" />, cls: "bg-slate-100 text-slate-600" },
}

export function NotificationCenter({ homeScreen }: { homeScreen: string }) {
  const notifs = useMyNotifications()
  const markRead = useStore((s) => s.markNotificationRead)
  const markAllRead = useStore((s) => s.markAllNotificationsRead)
  const navigate = useStore((s) => s.navigate)
  const unread = unreadCount(notifs)

  return (
    <div className="mx-auto w-full max-w-3xl space-y-4 p-4 sm:p-6">
      <SectionHeader
        title="Notifications"
        desc={`${unread} unread of ${notifs.length} total (demo notifications)`}
        action={unread > 0 ? <Button variant="outline" size="sm" onClick={markAllRead}><CheckCheck className="mr-1.5 h-4 w-4" /> Mark all read</Button> : undefined}
      />
      {notifs.length === 0 ? (
        <EmptyState icon={<Bell className="h-7 w-7" />} title="No notifications yet" desc="Activity like new free food nearby, request updates and alerts will appear here." />
      ) : (
        <div className="space-y-2">
          {notifs.map((n) => {
            const k = KIND_ICON[n.kind] ?? KIND_ICON.info
            return (
              <button
                key={n.id}
                onClick={() => {
                  markRead(n.id)
                  if (n.actionScreen) navigate(n.actionScreen)
                  else navigate(homeScreen)
                }}
                className={cn(
                  "flex w-full items-start gap-3 rounded-xl border p-3.5 text-left transition-colors active:bg-muted/60",
                  n.read ? "bg-card" : "border-emerald-200 bg-emerald-50/50",
                )}
              >
                <span className={cn("mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl", k.cls)}>{k.icon}</span>
                <span className="min-w-0 flex-1">
                  <span className="flex flex-wrap items-center gap-2">
                    <span className="text-sm font-bold leading-snug">{n.title}</span>
                    {!n.read && <span className="h-2 w-2 shrink-0 rounded-full bg-emerald-600" aria-label="unread" />}
                  </span>
                  <span className="mt-0.5 block text-xs leading-relaxed text-muted-foreground">{n.body}</span>
                  <span className="mt-1.5 flex items-center gap-2">
                    <span className="text-[10px] font-semibold text-muted-foreground">{timeAgo(n.at)}</span>
                    {n.actionScreen && <span className="rounded-full bg-emerald-600/10 px-2 py-0.5 text-[10px] font-bold text-emerald-700">View →</span>}
                  </span>
                </span>
              </button>
            )
          })}
        </div>
      )}
      <p className="text-center text-[10px] text-muted-foreground">
        Demo notification center — generated by demo actions and seeded demo events.
      </p>
    </div>
  )
}

export { StatusBadge }
